### PR TITLE
Add macro

### PR DESCRIPTION
**Pull request by khornem**
Hello,

First of all thank you for your great program.

I have changed the code in order to:
- add delay and move mouse cursor actions
- allow executing multiple actions sequentially after clicking a button (making macros)

Basically the code is the same, but instead of using a single vector for args and options I have converted them to vectors of vectors:
- each vector in each position of the parent vector contains all the actions that will be sequentially executed

I have not been able to block events in order it is captured by the daemon and not sent to the system (avoid that keys pressed perform both the programmed naga daemon action and default key action). In python I am able to grab a complete device (side buttons, by example), but I have not found the option in C++ yet.

### CODE REVIEW

**Comment by Destroyer** [comment]
Thanks for your work. I'll check it in the morning. But I want to ask what exactly do you mean by default key action? Like forward/back in browser? I've solved it by using lines 9-16 in nagastart.sh https://github.com/apocatarsis/Naga_KeypadMapper/blob/master/nagastart.sh#L9 , it's not exactly what you want but it works.

**Comment by khornem** [comment]
Hi,
Sorry I did not explained well. Your script works fine, but I wanted to block default action(like forward/back in browser) inside c code, not in shell script. That's what I meant.

**Comment by apocatarsis** [comment]
Thank you very much, khornem. Why do you think it is better to write macros directly in mapping.txt instead of mapping the button tu run some script?
The idea is cool, but I think it pollutes the mapping.txt and using a bash script gives you more options, right?.
I can see that by doing this you dont have to use xdotool directly in a script. Anyway this new functionality is completly retrocompatible and you can always just not use it. So if Destroyer and you are ok with it we will add it to the project!

On the other hand I do not understand the default key thing. You mean simply placing the "xinput set-int-prop" thingy inside the daemon code? I wouldn't worry about that, it seems rather useful to use canonical tools to obtain the ID, etc, of the device. So you might aswell just run that line in the script.


I am interested in the python thing. I initially wrote this in C++ because I read somewhere how to grab raw input from a device and I liked the idea. But I have the impression that this would be much easier, readable and automagical using python. And in a daemon as simple as this one performance doesn't seem like an issue. So please do tell us more. I can add you as a contributor if you'd like and open a python branch or something.

**Comment by khornem** [comment]
Hi,
I added macro functionality inside mapping because I thought that for some people it could be easier to avoid writing shell scripts. The main use is when you want to something like "click here and then there, and then ...".

I have made a python script (I have it in one of my repositories) that uses a json file as a configuration file. But I liked much your c script because it is cleaner. I am not a programmer and so my code is not very clean. The python code is in my repository NagaRazer. take a look at it and if you want I can add it as a  branch to your project.

**Comment by apocatarsis** [comment]
Wow, looks super pro! I like it. Thanks!

**Comment by apocatarsis** [comment]
BTW, about your pull request. Isn't it much better to use resize instead of push_back?
The code is very cool, you say you are not a programmer, but you seem to know how to program... 
I will add your changes to the repo when I have time. But either of you can do it if you want, I'd say a safe enhancement like this can go straight to master.

Thank you very much for your time and interest!
Again, I can add you as a contributor if you want.

**Comment by khornem** [comment]
Hi,
I don't know whether it is better resize instead of push_back. But with the second one I did not have to check vector lenght to avoid segmentation fault. So, although initially I used resize then I changed code for push_back. Besides, then the code was more similar to the initial code and thought it could be better for readability. As both codes are present in commit history we can use whatever version you like more.

About being a contributor, I will be pleased. However, I have never contribute to any project, so I do not exactly know how to make safely any changes, but I will study all the tutorials needed to avoid causing problems :)

**Comment by Destroyer** [comment]
Ok, this can go to testlab, but definitely not to master yet. There's at least one bug that I've found that caused my memory to be filled to 100% which is not great. ( http://i.imgur.com/U1Xsbmy.png ) 
I've solved it by calling before resizing vectors on line 77
`                args.clear();
                options.clear();`

**Comment by khornem** [comment]
Sorry for the bug. I did not notice. Happy you fix it so fast :)

**Comment by apocatarsis** [comment]
"About being a contributor, I will be pleased. However, I have never contribute to any project, so I do not exactly know how to make safely any changes". Yeah well neither do I. But Destroyer apears to be more experienced and is always helping me out with that!. For the mean time just commit and push to testlab and everything will be ok, when its safe, we will merge it with master. I will open a python branch, feel free to completly modify it as you want, I wont be touching it for the moment.

Super mega bug! Thanks Destroyer!, I did not went through the code... testlab it is then.

Thank you guys!

**Comment by apocatarsis** [comment]
BTW khornem. Please tell us what mouse and OS do you have. Does everything worked out of the box? what changes did you made to it in order to get it running?.

Tell us so we can add it to the README and the code if needed.
Thanks!

**Comment by khornem** [comment]
I use ubuntu 14.04.3.

My mouse is razer naga MMOG laser gaming mouse and it is detected as "naga molten" by the installation script (sorry if it is not the exact name, my brother just gave it to me when he bought an epic chroma mouse.). Product id is RZ01-0028.

It worked without any problems out of the box. So I did not have to apply any change.

**Comment by Destroyer** [comment]
I wouldn't call myself experienced, I had a c++ course in university two years ago and I'm still studying. The only thing I'm trying to do is to keep the code clean, understandable and fast so that everyone can make advantage of it, as well as make tweaks and changes to it (hopefully)without spending too much time figuring out how it works.

Btw since you guys are still writing here I don't wanna create another topic in issues or somewhere else. I think we can merge changes to master to this commit be857034ca4e40e16c52a541b4f3eb688f3fc8e1 . But I am not that familiar with git, does someone know how to cherry pick those commits and fix possible conflicts?

**Comment by khornem** [comment]
I am not a git expert, but I understand that you want to merge master to that commit, without including last modifications.
As far as I now merges can only be done to full branches, not to specific commits. So you will have to create a new branch for that merge:

    git checkout -b merge-point be85703

Then you have to ckeckout to master and pull latest master changes:

    git checkout master
    git pull origin master

Then you can merge master branch and that commit. I have tried it locally in my computer and have seen that there are conflicts:

    miguel@vaio:~/tmp/naga/Naga_KeypadMapper$ git checkout master 
    Switched to branch 'master'
    Your branch is up-to-date with 'origin/master'.
    miguel@vaio:~/tmp/naga/Naga_KeypadMapper$ git merge merge-point 
    Auto-merging src/naga.cpp
    CONFLICT (content): Merge conflict in src/naga.cpp
    Auto-merging nagastart.sh
    Auto-merging README.md
    CONFLICT (content): Merge conflict in README.md
    Automatic merge failed; fix conflicts and then commit the result.
    miguel@vaio:~/tmp/naga/Naga_KeypadMapper$ git status
    On branch master
    Your branch is up-to-date with 'origin/master'.
    
    You have unmerged paths.
      (fix conflicts and run "git commit")
    
    Changes to be committed:
    
        modified:   nagastart.sh
    
    Unmerged paths:
      (use "git add <file>..." to mark resolution)
    
        both modified:      README.md
        both modified:      src/naga.cpp
    
    miguel@vaio:~/tmp/naga/Naga_KeypadMapper$ 


In order to solve conflicts you have to edit both README.md and naga.cpp.
You will find in those files sections like this one:

    <<<<<<< HEAD
    This lasts until the x server is restarted (`nagastart.sh` is aware of this), but you can enable it back to completly restore the changes by changing the last 0 to a 1 in 2).
    =======
    This lasts until the x server is restarted (`nagastart.sh` is aware of this), but you can enable it back to completely restore the changes by changing the last 0 to a 1.
    >>>>>>> merge-point

You will have to select which section do you prefer, the one in master (from <<<<HEAD to ===) or the one in merge-point (the other section), or even any other code or text.

Once you have fix all those conflicts you have to commit changes. Once you commit changes branches will be merged and you can push master to github repository.

    *   commit bc84b8bd31053eb271d8b44a31482abfd0a3f0b0 (HEAD, master)
    |\  Merge: 85eea2f be85703
    | | Author: khornem <--->
    | | Date:   Sun Jan 31 00:09:25 2016 +0100
    | | 
    | |     fix conflicts and merge
    | |   
    | * commit be857034ca4e40e16c52a541b4f3eb688f3fc8e1 (merge-point)
    | | Author: Vlach Miroslav <--->
    | | Date:   Thu Dec 31 19:12:54 2015 +0100
    | | 
    | |     Improved code readability and updated README.md
    | |     Moved variables that are used only in one method to that method. Added consts.
    | |     Added more info about how to bind a key to the readme, also fixed some typos.
    | |   
    | * commit b14735392e10923a54debeddbb21a1f1b7fff93e
    | | Author: Destroyer954 <--->
    | | Date:   Wed Sep 16 17:55:13 2015 +0200
    | | 
    | |     Fixes a crash when pressing extra buttons
    | |   
    | * commit 040ab44e64a2bf497feedd5842307953780f8de7
    | | Author: Destroyer954 <--->
    | | Date:   Wed Sep 16 14:29:29 2015 +0200
    | | 
    | |     Revert nagastart.sh
    | |   
    | * commit 6ab4b28a3974f61928ec484803fe27943d8ed91a
    | | Author: Destroyer954 <--->
    | | Date:   Wed Sep 16 14:27:42 2015 +0200
    | | 
    | |     More switches, also reduce CPU usage to minimum, fixes #11
    | |   
    * | commit 85eea2f6aac6bf89f793a00e7ac2388023ac0b76 (origin/master, origin/HEAD)
    | | Author: Apocatarsis <--->
    | | Date:   Sat Jan 30 15:54:19 2016 +0100
    | | 
    | |     Added Chroma support, fixed installation issues and use .bash_profile instead .desktop for portability when autostart
    | |   
    * | commit e0c8fbfc29b56c1a6e979a07780c82ea176f616c
    | | Author: Apocatarsis <--->
    | | Date:   Sat Jan 30 15:19:04 2016 +0100
    | | 
    | |     Added Chroma support, fixed installation issues and use .bash_profile instead .desktop for portability when autostart
    | |   
    * | commit 8d32a150294edbc84140a1c0be9975835f984e9b
    | | Author: apocatarsis <--->
    | | Date:   Tue Sep 15 11:02:54 2015 +0200
    | | 
    | |     Obselete
    | |   
    * | commit eaef1d432af2fdfd80c8c8a363f0526ae4760d15
    |/  Author: RaulPPelaez <--->
    |   Date:   Tue Sep 15 10:47:05 2015 +0200
    |   
    |       After merging with Destroyer's version
    |  
    * commit 0ed29df29e9caf072a6b9049b8e883d6b21c8b60

**Comment by khornem** [comment]
One last comment. My recommendation is that you make these changes in another local directory different from the one you are using to code:
- git clone on another directory
- make all merging in that directory
if it works push the results, otherwise delete and begin again.

This is the method recommended by xkcd https://xkcd.com/1597/ ;)

**Comment by Destroyer** [comment]
That didn't end up working for me as I was hoping for because of those formatting changes. So I went with CLion and formated the code automatically so now it should be perfect. 

Anyway I think that my job is done here and it can be merged with master (you can test it for yourself before doing so). Only one thing that bothers me is the implementation of delays. Since we're running the entire thing in a single thread when delay is used we can't process another command simultaneously. This still needs extra script. On the other side I don't want to spawn another thread for executing one or few commands every time user clicks so I'm leaving it that way.

**Comment by apocatarsis** [comment]
Thanks!! I usually use the xkcd method at work...

Yeah sorry Destroyer, I might have screwed up the formatting a little, I guess git doesnt like it. I'm in the foo(){ club...
I checked and the chroma thing seems in order. The autostart issue is yer to be definetly solved.

**Pull request merged**
